Repository tryber/sd-09-project-trivia-react-redux, pull requests merged in 2021-04, with the labels that each got.

#9 Redux
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/components/Com.jsx
  src/index.js
  src/pages/Home.jsx
  src/redux/actions/index.js
  src/redux/reducer/index.js
  src/redux/store/index.js
Labels: Code Review

#13 [GROUP 26] Starts project
  README.md
  package-lock.json
  package.json
  src/App.js
Labels: Code Review

#22 Group 24 requirement 01
  package-lock.json
  package.json
  src/App.js
  src/actions/actionTypes.js
  src/actions/index.js
  src/components/Header.jsx
  src/index.js
  src/pages/Login.jsx
  src/reducers/index.js
  src/reducers/loginReducer.js
  src/store/index.js
Labels: Code Review

#24 [GROUP 26] Requirement 1: adds inputs
  src/App.js
  src/actions/index.js
  src/components/Header.js
  src/index.js
  src/pages/Feedback.js
  src/pages/Login.js
  src/pages/Questions.js
  src/pages/Rank.js
  src/reducers/index.js
  src/services/api.js
  src/store/index.js
Labels: Code Review

#29 Main group 33 requisito 1
  README.md
  package-lock.json
  package.json
  src/App.js
  src/index.js
  src/pages/Login.js
  src/reducers/index.js
  src/store/index.js
Labels: Code Review

#42 Finishing requirement 03.
  src/App.js
  src/pages/Login.jsx
  src/pages/Settings.jsx
Labels: Code Review

#75 [GRUPO 33] Projeto Trivia - Requisito 02
  package-lock.json
  package.json
  src/App.js
  src/actions/index.js
  src/index.js
  src/pages/Game.jsx
  src/pages/Login.js
  src/reducers/gameToken.js
  src/reducers/index.js
  src/services/index.js
  src/store/index.js
Labels: Code Review

#77 [Group-8][Req. 02: Add play button]
  src/components/Login.jsx
  src/index.js
Labels: Code Review

#62 [Grupo 9 ] requisito 1 e 2
  src/App.js
  src/pages/GamePage.jsx
  src/pages/Login.jsx
  src/redux/actions/index.js
  src/redux/reducer/index.js
  src/redux/reducer/trivia.js
Labels: Code Review

#90 Main group 9 req5
  package-lock.json
  src/App.js
  src/components/Com.jsx
  src/pages/Config.jsx
  src/pages/GamePage.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/redux/actions/index.js
  src/redux/reducer/gameReducer.js
  src/redux/reducer/index.js
Labels: Code Review

#65 Grupo 01 trivia main devop structure
  src/App.js
  src/Pages/Home.js
  src/Pages/Login.js
  src/Pages/Trivia.js
Labels: Code Review

#39 [Grupo 21] - Começando projeto!!
  package-lock.json
  package.json
  src/App.js
  src/components/LoginForm.js
  src/index.js
  src/pages/Login.js
  src/reducers/index.js
  src/reducers/user.js
  src/store/index.js
Labels: Code Review

#105 [Group-15][Req-1]
  src/App.js
  src/index.js
  src/pages/Login.js
  src/redux/actions/index.js
  src/redux/reducers/index.js
  src/redux/store/index.js
Labels: Code Review

#108 Main group 21 requisito 2
  src/App.js
  src/actions/index.js
  src/components/LoginForm.js
  src/pages/GamePage.js
  src/reducers/user.js
Labels: Code Review

#107 add settings page and button link to settings page
  package-lock.json
  src/App.js
  src/pages/Login.jsx
  src/pages/Settings.jsx
Labels: Code Review

#96 Feat/Req3
  package-lock.json
  src/App.js
  src/components/Login.jsx
  src/pages/Settings.jsx
Labels: Code Review

#128 Feito Req 2-Group 15
  src/App.js
  src/index.js
  src/pages/Game.js
  src/pages/Login.js
  src/redux/actions/index.js
  src/redux/reducers/index.js
  src/redux/reducers/login.js
  src/redux/store/index.js
  src/service/Api.js
Labels: Code Review

#85 [Grupo 31] Requisito 0 - Cria estrutura inicial da aplicação
  package-lock.json
  package.json
  src/actions/index.js
  src/actions/types.js
  src/pages/Feedback.js
  src/pages/Game.js
  src/pages/Login.js
  src/pages/Ranking.js
  src/pages/Settings.js
  src/reducers/index.js
  src/services/index.js
  src/store/index.js
Labels: Code Review

#132 G6 feat requirement 8
  src/components/BooleanAnswers.js
  src/components/MultipleAnswers.js
  src/pages/Game/Game.js
  src/redux/actions/actionDecreaseTime.js
  src/redux/actions/actionTypes.js
  src/redux/reducers/questionsReducer.js
Labels: Code Review

#131 [Main group 9] requisito 12
  src/pages/Feedback.jsx
Labels: Code Review

#140 [Main group 9] requisito 13
  src/pages/Feedback.jsx
Labels: Code Review

#71 [Grupo 9] requisito 4
  package-lock.json
  package.json
  src/components/Header.jsx
  src/pages/GamePage.jsx
  src/pages/Login.jsx
  src/redux/actions/index.js
  src/redux/reducer/trivia.js
Labels: Code Review

#145 Main group 17 req01 & 02
  README.md
  package-lock.json
  package.json
  src/App.js
  src/actions/index.js
  src/index.js
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/reducers/index.js
  src/reducers/tokenReducer.js
  src/services/index.js
  src/store/index.js
Labels: Code Review

#118 Main group 22 feat/requisito 12
  README.md
  package-lock.json
  package.json
  src/components/FeedbackHeader.jsx
Labels: Code Review

#149 [Main group 9] requisito 14
  src/pages/Feedback.jsx
Labels: Code Review

#99 main-group-22-feat/requisito-03
  src/components/SettingsButton.jsx
  src/pages/Settings.jsx
Labels: Code Review

#160 [GRUPO 33] Projeto Trivia - Requisito 04
  src/actions/index.js
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/reducers/gameToken.js
  src/reducers/index.js
  src/reducers/player.js
Labels: Code Review

#173 Main group 21 requisitos 5 e 6
  src/App.js
  src/components/Gameplay.js
  src/components/LoginForm.js
  src/pages/GamePage.js
  src/pages/index.js
  src/services/index.js
Labels: Code Review

#133 [GRUPO 16] HABEMUS TRIVIA TELA DE LOGIN
  package-lock.json
  package.json
  src/App.js
  src/actions/index.js
  src/index.js
  src/pages/login.jsx
  src/reducers/index.js
  src/store/index.js
Labels: Code Review, developing

#137 [GRUPO34][REQUISITO01] - Crie a tela de login, onde a pessoa que joga deve preencher as informações para iniciar um jogo.
  README.md
  package-lock.json
  package.json
  src/App.js
  src/index.js
  src/pages/Game.js
  src/pages/login.js
  src/redux/actions/index.js
  src/redux/reducers/index.js
  src/redux/reducers/loginReducer.js
  src/redux/store/index.js
  src/services/triviaApi.js
Labels: Code Review

#194 [GROUP 26] Requirement 4
  src/App.js
  src/components/Header.js
  src/pages/Login.js
  src/pages/Questions.js
Labels: Code Review

#204 [GRUPO 9] - Ex. 8 - Timer
  src/components/Header.jsx
  src/components/Timer.jsx
  src/pages/GamePage.jsx
  src/pages/Login.jsx
  src/redux/actions/index.js
  src/redux/reducer/gameReducer.js
Labels: Code Review

#224 G6 feat requirement 10 - Parcialmente Completo
  src/components/BooleanAnswers.js
  src/components/MultipleAnswers.js
  src/pages/Game/Game.js
  src/redux/actions/actionDisableButton.js
  src/redux/actions/actionResetCounter.js
  src/redux/actions/actionResetFunction.js
  src/redux/actions/actionShowButton.js
  src/redux/actions/actionTypes.js
  src/redux/reducers/questionsReducer.js
Labels: Code Review, developing

#243 feat/store receives token
  src/actions/index.js
  src/pages/Login.js
  src/reducers/playerReducer.js
Labels: Code Review

#249 [grupo 6] conserta requisito 10
  src/App.js
  src/components/BooleanAnswers.js
  src/components/MultipleAnswers.js
  src/pages/Feedback/Feedback.js
  src/pages/Game/Game.js
  src/redux/reducers/questionsReducer.js
Labels: Code Review

#241 requisito 5
  src/actions/index.js
  src/components/CardQuestion.jsx
  src/pages/Game.jsx
  src/reducers/gameQuestions.js
  src/reducers/gameToken.js
  src/reducers/index.js
  src/services/index.js
Labels: Code Review

#257 G6 fix bugs requirement 11
  src/components/MultipleAnswers.js
  src/pages/Game/Game.js
  src/redux/actions/actionAddOptionAnswers.js
  src/redux/actions/actionCleanOptionAnswers.js
  src/redux/actions/actionTypes.js
  src/redux/reducers/answersReducer.js
  src/redux/reducers/index.js
Labels: Code Review

#245 [Group 30]Feat/Requirement7
  src/pages/ScreenGame.jsx
Labels: Code Review

#236 Main group 9 requisito 11 e 10
  package-lock.json
  package.json
  src/App.js
  src/components/Timer.jsx
  src/pages/Feedback.jsx
  src/pages/GamePage.jsx
Labels: Code Review

#268 [Group-15] - Requirement 7
  src/pages/components/Questions.js
  src/styles/components/Questions.css
Labels: Code Review

#238 requisito 05 - Buscando dados da api de questões e renderizando
  src/App.js
  src/actions/index.js
  src/components/Answers.jsx
  src/pages/Game/Game.jsx
  src/pages/Game/game.css
  src/pages/Login.jsx
  src/reducers/actionsReducers.js
  src/reducers/index.js
  src/reducers/tokenReducer.js
  src/services/index.js
Labels: Code Review

#253 Main group 16 criando header
  package-lock.json
  src/actions/loginAction.js
  src/components/Header.css
  src/components/Header.jsx
  src/pages/Game.js
  src/reducers/loginReducer.js
Labels: Code Review

#175 g28-requisito 4 feito
  src/App.js
  src/actions/index.js
  src/components/Header.js
  src/components/HeaderUser.js
  src/components/LoginForm.js
  src/components/StartGameButton.js
  src/components/index.js
  src/pages/QuestionPage.js
  src/pages/index.js
  src/reducers/user.js
  src/services/api.js
Labels: Code Review

#288 [Group-15] - Requirement 8
  src/pages/Game.js
  src/pages/components/Questions.js
  src/pages/components/Timer.js
  src/redux/actions/index.js
  src/redux/reducers/index.js
  src/redux/reducers/timer.js
Labels: Code Review

#294 g28-requisito 5
  src/actions/index.js
  src/components/Header.js
  src/components/QuestionBool.js
  src/components/QuestionMultiple.js
  src/components/index.js
  src/pages/QuestionPage.css
  src/pages/QuestionPage.js
  src/reducers/index.js
  src/reducers/trivia.js
  src/services/api.js
Labels: Code Review

#219 Main group 31.req 1
  package-lock.json
  package.json
  src/App.js
  src/actions/index.js
  src/actions/types.js
  src/index.js
  src/pages/Login.js
  src/reducers/index.js
  src/reducers/user.js
  src/store/index.js
Labels: Code Review

#292 [GROUP2][FEAT][REQ12]
  src/Redux/actions/index.js
  src/Redux/reducers/index.js
  src/Redux/reducers/score.js
  src/components/FeedbackHeader.jsx
Labels: Code Review

#312 [Grupo 9] req9
  src/pages/Feedback.jsx
  src/pages/GamePage.jsx
  src/pages/Login.jsx
Labels: Code Review

#315 [grupo 6] adiciona componente Header e Botão de ir ao inicio
  src/components/Header/Header.js
  src/pages/Feedback/Feedback.js
  src/pages/Game/Game.js
  src/pages/Login/Login.js
  src/redux/actions/actionTypes.js
  src/redux/reducers/questionsReducer.js
Labels: Code Review

#240 [Group 30] [FEAT] [Requirement 10]
  src/components/NextQuestionButton.jsx
  src/pages/ScreenGame.jsx
  src/styles/styleButonsAnswers.css
Labels: Code Review

#318 Main group 9 req17
  src/App.js
  src/pages/Ranking.jsx
Labels: Code Review

#321 g28-requisito 7 feito
  src/components/NextButton.js
  src/components/QuestionBool.js
  src/components/QuestionMultiple.js
Labels: Code Review

#319 Main group 16 estilizando header
  public/index.html
  src/components/Header.css
  src/components/Header.jsx
Labels: Code Review

#326 [Grupo 9] fix Requisito 18
  src/components/GoHome.jsx
  src/pages/Ranking.jsx
Labels: Code Review

#343 g28-fix-ESLINT
  src/components/Header.js
  src/components/LoginForm.js
  src/components/QuestionBool.js
  src/components/QuestionMultiple.js
  src/components/StartGameButton.js
  src/components/index.js
  src/pages/Login.css
  src/pages/Login.js
  src/pages/QuestionPage.css
  src/pages/QuestionPage.js
  src/pages/Settings.css
Labels: Code Review

#328 Main group 16 game page
  src/App.js
  src/actions/index.js
  src/actions/loginAction.js
  src/actions/triviaAction.js
  src/pages/Game.js
  src/pages/Login.js
  src/reducers/index.js
  src/reducers/loginReducer.js
  src/reducers/triviaReducer.js
  src/services/tokenAPI.js
  src/services/triviaAPI.js
Labels: Code Review

#304 [GRUPO 33] Projeto Trivia - Requisito 06
  src/actions/index.js
  src/components/CardQuestion.jsx
  src/components/Loading.jsx
  src/components/PlayerHeaderInfo.jsx
  src/pages/Game.jsx
  src/reducers/gameQuestions.js
Labels: Code Review

#366 add css case selectAnswer
  src/components/CardQuestion.css
  src/components/CardQuestion.jsx
Labels: Code Review

#355 [Group2][Feat][Req7]
  src/Redux/actions/index.js
  src/Redux/reducers/index.js
  src/Redux/reducers/questions.js
  src/Redux/reducers/score.js
  src/components/EachQuestion.jsx
  src/components/FeedbackHeader.jsx
  src/components/LoginForm.jsx
  src/components/Questions.jsx
  src/components/index.js
  src/pages/Feedback.js
  src/pages/GamePage.jsx
Labels: Code Review

#351 [Grupo 31] (feat) Adiciona requisito 2
  package-lock.json
  package.json
  src/actions/trivia.js
  src/actions/types.js
  src/pages/Login.js
  src/reducers/index.js
  src/reducers/trivia.js
  src/services/api.js
  src/services/index.js
Labels: Code Review

#385 [Grupo 6] requisito 17
  src/App.css
  src/components/MultipleAnswers.js
  src/pages/Feedback/Feedback.js
  src/pages/Ranking/Ranking.js
Labels: Code Review

#388 Requirement 7.
  src/index.css
  src/pages/Game.jsx
Labels: Code Review

#397 [FEAT][Requisitos 8 ao 12]
  src/App.js
  src/actions/index.js
  src/components/Answers.jsx
  src/components/Header.jsx
  src/pages/Feedback.jsx
  src/pages/Game/game.css
  src/pages/Login.jsx
  src/reducers/index.js
  src/reducers/playerReducer.js
Labels: developing

#404 [Grupo 21] - Requisito 4
  package-lock.json
  src/components/Gameplay.js
  src/components/HeaderGamePlay.js
  src/pages/GamePage.js
Labels: Code Review

#412 [Grupo 31] (feat) Merge requisitos 2 a 5
  package-lock.json
  package.json
  src/pages/Game.js
Labels: Code Review

#423 [Grupo 31] fix(user reducer): Corrige estado no store
  src/reducers/user.js
Labels: Code Review

#418 implements timer and disable answers when 30s is passed
  src/Componentes/Question.js
  src/pages/Game.js
Labels: Code Review

#433 g28-feat-timer
  src/App.js
  src/actions/index.js
  src/components/Header.js
  src/components/LoginForm.js
  src/components/Question.js
  src/components/QuestionBool.js
  src/components/QuestionMultiple.js
  src/components/SettingsButton.js
  src/components/StartGameButton.js
  src/components/index.js
  src/pages/Login.js
  src/pages/QuestionPage.js
  src/pages/Ranking.css
  src/pages/Ranking.js
  src/pages/index.js
  src/reducers/trivia.js
  src/services/api.js
Labels: Code Review

#439 [Group-15] - Requirement 9
  cypress/integration/project.spec.js
  package-lock.json
  src/pages/Login.js
  src/pages/components/Header.js
  src/pages/components/Questions.js
  src/pages/components/Timer.js
  src/redux/actions/index.js
  src/redux/reducers/index.js
  src/redux/reducers/player.js
  src/redux/reducers/timer.js
Labels: Code Review

#441 G6 ranking style
  src/App.css
  src/pages/Ranking/Ranking.js
  src/pages/Ranking/ranking.css
Labels: Code Review

#448 [Group 8] [req.7-9: Add score and assertions calc functions]
  cypress/integration/project.spec.js
  src/components/GamePlayHeader.jsx
  src/components/Login.jsx
  src/components/Question.css
  src/components/Question.jsx
  src/components/Timer.jsx
  src/redux/actions/index.js
  src/redux/reducers/triviaReducer.js
Labels: Code Review

#442 [Grupo 31] Adiciona requisitos 6 e 7
  src/App.js
  src/components/Question.js
  src/pages/Game.js
  src/pages/Login.js
Labels: Code Review

#468 g28-requisitos-13-15-18-feitos
  src/components/Header.js
  src/pages/Feedback.css
  src/pages/Feedback.js
  src/pages/FeedbackPage.js
  src/pages/QuestionPage.js
  src/pages/Ranking.js
  src/pages/index.js
  src/reducers/user.js
Labels: Code Review

#456 estilo do botão finalizado
  package-lock.json
  package.json
  public/index.html
  src/pages/Login/Login.css
  src/pages/Login/Login.js
  src/utils/img/TRIVIA-GAME.png
Labels: Code Review

#420 Feat/Requirement15
  cypress/integration/project.spec.js
  src/components/Header.jsx
  src/pages/Feedback.jsx
Labels: Code Review

#463 [FEAT] [Requisito 16] [Grupo 30]
  src/App.js
  src/pages/Feedback.jsx
  src/pages/Ranking.jsx
Labels: Code Review

#467 Group 24 requirement 8
  src/App.js
  src/actions/actionTypes.js
  src/actions/index.js
  src/components/Header.jsx
  src/components/Timer.jsx
  src/pages/Feedback.jsx
  src/pages/Game.jsx
  src/pages/Ranking.jsx
  src/reducers/index.js
  src/reducers/timerReducer.js
Labels: Code Review

#475 [Group 30] [FEAT] [Requisito 17]
  src/pages/Ranking.jsx
  src/pages/ScreenGame.jsx
Labels: developing

#480 organização de componentes
  src/App.js
  src/components/SettingsButton.js
  src/components/StartGameButton.js
  src/components/index.js
  src/pages/Login.js
  src/pages/Trivia.css
  src/pages/Trivia.js
  src/pages/index.js
Labels: Code Review

#492 g28 ajustes no redux
  src/actions/index.js
  src/pages/Feedback.js
  src/reducers/user.js
Labels: Code Review

#485 Main group 9 configurations
  cypress/integration/project.spec.js
  src/pages/Config.jsx
  src/pages/GamePage.jsx
  src/pages/Login.jsx
  src/redux/actions/index.js
  src/redux/reducer/trivia.js
  src/service/API.js
Labels: Code Review

#515 Implementa req 18
  src/App.js
  src/pages/Feedback.js
  src/pages/Game.js
Labels: Code Review

#469 [group-8][Req. 11 - 16: Add 5 question rule, Feedback and Ranking pages]
  src/App.js
  src/components/Feedback.jsx
  src/components/FeedbackHeader.css
  src/components/FeedbackHeader.jsx
  src/components/GamePlay.jsx
  src/components/Ranking.jsx
Labels: Code Review

#517 req-15-and-fix-timer
  cypress/integration/project.spec.js
  package-lock.json
  src/Componentes/Question.js
  src/pages/Feedback.js
  src/pages/Game.js
Labels: Code Review

#527 [ FEAT ][ GRUPO 19 ] Apenas uma alternatica certa por questão
  src/components/Answer.jsx
  src/components/Question.jsx
  src/components/Questions.jsx
Labels: Code Review

#513 [Grupo 31] (Game) Adiciona requisito 8
  src/components/Question.js
Labels: Code Review

#541 [Main group 17][FEAT 08,09,13 & 14]
  cypress/integration/project.spec.js
  src/components/Answers.jsx
  src/components/Timer.jsx
  src/pages/Feedback.jsx
  src/pages/Game/Game.jsx
Labels: Code Review

#542 [Group-15] - Requirement 11
  src/App.js
  src/pages/Feedback.js
  src/pages/components/Questions.js
  src/pages/components/Timer.js
  src/redux/actions/index.js
  src/redux/reducers/timer.js
Labels: Code Review

#392 Group 13 - Requisito 05
  package-lock.json
  src/App.js
  src/App.test.js
  src/pages/Login.jsx
  src/pages/Question.jsx
  src/pages/css/question.css
  src/redux/actions/index.js
  src/redux/reducers/gameReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/loginReducer.js
  src/services/gameAPI.js
  src/services/triviaApi.js
Labels: developing

#555 Feito requisito 13
  src/pages/Feedback.js
  src/pages/components/Questions.js
Labels: Code Review

#545 Estilizando componentes
  src/App.css
  src/components/configButton.css
  src/components/configButton.js
  src/img/questao.png
  src/img/settings.png
  src/img/wave-bottom.svg
  src/img/wave-top.svg
  src/pages/Game.js
  src/pages/Login.js
  src/pages/game.css
  src/pages/login.css
Labels: Code Review

#568 Main group 16 timer
  src/pages/Game.js
Labels: Code Review

#571 feat(./components/Questions): adiciona requisitos 10 - 11
  src/components/Question.js
  src/pages/Game.js
  src/services/score.js
  src/services/storage.js
Labels: Code Review

#585 [FEAT][Requisito 09][Cria placar do jogo][V1.0]
  src/actions/index.js
  src/actions/loginAction.js
  src/actions/playerAction.js
  src/components/Header.jsx
  src/pages/Game.js
  src/pages/Login.js
  src/reducers/index.js
  src/reducers/playerReducer.js
Labels: Code Review

#590 [Feat][Requisito 10][Cria botão Next][V1.0]
  src/pages/Game.js
Labels: Code Review

#593 Main group 16 redirect to feedback
  src/App.js
  src/pages/Feedback.js
  src/pages/Game.js
Labels: Code Review

#605 Main group 21 cria feedback score
  src/pages/FeedbackPage.js
Labels: Code Review

#598 Group 13 - Requisito 7
  package-lock.json
  package.json
  src/pages/Question.jsx
  src/pages/css/question.css
Labels: developing

#573 requisitos bonus feitos
  src/actions/index.js
  src/components/Question.js
  src/pages/Settings.js
  src/pages/Trivia.js
  src/reducers/index.js
  src/reducers/settings.js
  src/services/api.js
Labels: Code Review

#620 [FIX][Game.js][Conserta bug ao clicar em respostas do jogo e remove outlines no CSS][V1.0]
  src/pages/Game.js
  src/pages/game.css
  src/pages/login.css
Labels: Code Review

#624 [Grupo 33] Requisito 9
  src/components/CardQuestion.jsx
Labels: Code Review

#635 [GRUPO 26] Requisito 16 - Cria `<Link />` para pagina de ranking
  src/pages/Feedback.js
Labels: Code Review

#565 [GRUPO 26] Requisito 17 - Cria tela de ranking
  src/App.js
  src/pages/Questions.js
  src/pages/Rank.js
  src/services/gravatar.js
  src/services/localStorage.js
Labels: Code Review

#603 Main group 31.req 17
  src/App.js
  src/pages/Feedback.js
  src/pages/Ranking.js
Labels: Code Review

#612 [Grupo 31] (Settings) Adiciona requisitos bônus
  src/actions/settings.js
  src/actions/trivia.js
  src/actions/types.js
  src/pages/Game.js
  src/pages/Login.js
  src/pages/Settings.js
  src/reducers/index.js
  src/reducers/settings.js
  src/services/api.js
Labels: Code Review

#634 [GRUPO 33] Projeto Trivia - Requisitos 12 e 13
  src/actions/index.js
  src/components/CardQuestion.jsx
  src/components/FeedbackContent.jsx
  src/pages/Feedback.jsx
  src/reducers/player.js
Labels: Code Review

#647 Group 13 - Requisito 15
  src/pages/Feedback.jsx
  src/pages/Question.jsx
  src/pages/components/CountdownTimer.jsx
  src/pages/css/feedback.css
  src/pages/css/login.css
  src/pages/css/question.css
  src/pages/css/timer.css
Labels: Code Review

#644 [ESTILIZACAO][ajustes na largura das waves - medidas responsivas][V5]
  src/img/perder.png
  src/img/trofeu.png
  src/pages/Feedback.js
  src/pages/Game.js
  src/pages/feedback.css
  src/pages/game.css
Labels: Code Review

#655 [Grupo 31] Requisitos 15-16-18 by Jorge William
  src/pages/Feedback.js
  src/pages/Login.js
  src/pages/Ranking.js
Labels: Code Review

#656 [Grupo 33] Requisito 14
  src/actions/index.js
  src/components/PlayerHeaderInfo.jsx
Labels: Code Review

#665 [Grupo 31] Adiciona estilos
  src/App.css
  src/App.js
  src/components/ButtonSettings.js
  src/components/ButtonSettings.module.css
  src/components/Header.js
  src/components/Header.module.css
  src/components/Question.js
  src/components/Question.module.css
  src/components/Score.js
  src/components/Score.module.css
  src/components/Timer.js
  src/components/Timer.module.css
  src/img/at.png
  src/img/config.png
  src/img/crown.png
  src/img/user.png
  src/pages/Feedback.js
  src/pages/Feedback.module.css
  src/pages/Login.js
  src/pages/Login.module.css
  src/pages/Ranking.js
  src/pages/Ranking.module.css
  src/pages/Settings.js
  src/pages/Settings.module.css
Labels: Code Review

#675 [GROUP - 15] - Requirement 17 and 18
  src/App.js
  src/pages/Feedback.js
  src/pages/Ranking.js
  src/pages/components/Header.js
  src/pages/components/Questions.js
  src/pages/components/Timer.js
  src/redux/actions/index.js
  src/redux/reducers/player.js
  src/redux/reducers/timer.js
Labels: Code Review

#671 [Group-15] - Requirement 16
  src/App.js
  src/pages/Feedback.js
  src/pages/Ranking.js
  src/pages/components/Questions.js
Labels: Code Review
